config/routes.rb
Galeery::Application.routes.draw do
  resources :images

  get "home/index"

 root :to => "home#index"

end

app/models/image.rb
class Image < ActiveRecord::Base
has_attached_file :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  # GET /images
  # GET /images.xml
  def index
    @images = Image.paginate(:page => params[:page], :per_page => 2)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @images }
    end
  end

  # GET /images/1
  # GET /images/1.xml
  def show
    @image = Image.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/new
  # GET /images/new.xml
  def new
    @image = Image.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @image }
    end
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  # POST /images.xml
  def create
    @image = Image.new(params[:image])

    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /images/1
  # PUT /images/1.xml
  def update
    @image = Image.find(params[:id])

    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.xml
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/home/index.html.erb
<center><h1> Friends list <h1></center>
<hr/>
<h4><font color=white>To add friend please click on</font> <%= link_to "Friends", images_path %></h4>
<h1><img alt="Friends" src="/images/friends.gif"/></h1><br>

<hr/>

app/views/images/_form.html.erb
<%= form_for(@image, :html => { :multipart => true } ) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h1 align=left><img src="friend.jpg" align=left width=200 height=200></h1><br>

<center>
<table border=1>
<tr bgcolor=green>
<td>
 
    <%= f.label :friend_name %><br />
</td>
<td>
    <%= f.text_field :friend_name %>
 </td>

 <tr bgcolor=green>
<td>
    <%= f.label :friend_mobile %><br />
</td>
<td>
    <%= f.text_field :friend_mobile %>
</td>
  </tr>
<tr bgcolor=green>
 <td>
    <%= f.label :friend_address %><br />
</td>
<td>
    <%= f.text_area :friend_address %>
</td>
  </tr>
 <tr bgcolor=green>
<td>
    <%= f.label :friend_date__of_birth %><br />
</td>
<td>
    <%= f.date_select :friend_date__of_birth %>
  </td>
</tr>
<tr bgcolor=green>
<td>Image_upload</td>
<td>
<%= f.file_field :avatar %>
</td>
</tr>
</table>
</center>
<center>
  <div class="actions">
    <%= f.submit %>
  </div>
</center>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<h1>My Friends</h1>


<% @images.each do |image| %>
<table>
  <tr>
    <td>Friend name</td>
    <td><%= link_to "#{image.friend_name}", image %>&nbsp;&nbsp;<%= link_to 'Edit', edit_image_path(image) %>|<%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %> </td>
</tr>
<tr>
    <td>Friend mobile</td>
<td><%= image.friend_mobile %></td>
</tr>
<tr>
    <td>Friend address</td>
<td><%= image.friend_address %></td>
</tr>
<tr>
    <td>Friend date  of birth</td>
<td><%= image.friend_date__of_birth %></td>
</tr>
</table>
<br/>
<% end %>

<%= will_paginate @images %>
<br />

<%= link_to 'Add Friend', new_image_path %>

app/views/images/new.html.erb
<center><h1>My Friend</h1></center>
<hr/>
<h2><%= link_to 'Back', images_path %></h2>
<%= render 'form' %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Friend name:</b>
  <%= @image.friend_name %>
</p>

<p>
  <b>Friend mobile:</b>
  <%= @image.friend_mobile %>
</p>

<p>
  <b>Friend address:</b>
  <%= @image.friend_address %>
</p>

<p>
  <b>Friend date  of birth:</b>
  <%= @image.friend_date__of_birth %>
</p>
<p>
<%= image_tag @image.avatar.url %>
<%= image_tag @image.avatar.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Galeery</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>